spring:  
  datasource:
    mochi:
      application: 
        max-lifetime: ${SPRING_DATASOURCE_MAX_LIFETIME}
        maximum-pool-size: ${SPRING_DATASOURCE_MAX_POOL_SIZE} 
        connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT}
        minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE}
        url: ${SPRING_MOCHI_DATASOURCE_URL}
        username: ${SPRING_MOCHI_APP_DATASOURCE_USERNAME}
        password: ${SPRING_MOCHI_APP_DATASOURCE_PASSWORD} 
        driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS}
     
      owner:
        max-lifetime: ${SPRING_DATASOURCE_MAX_LIFETIME}
        maximum-pool-size: ${SPRING_DATASOURCE_MAX_POOL_SIZE} 
        connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT}
        minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE}
        url: ${SPRING_MOCHI_DATASOURCE_URL}
        username: ${SPRING_MOCHI_OWN_DATASOURCE_USERNAME}
        password: ${SPRING_MOCHI_OWN_DATASOURCE_PASSWORD}
        driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS}
      
    security: 
      application:
        max-lifetime: ${SPRING_DATASOURCE_MAX_LIFETIME}
        maximum-pool-size: ${SPRING_DATASOURCE_MAX_POOL_SIZE} 
        connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT}
        minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE}
        url: ${SPRING_SECURITY_DATASOURCE_URL}
        username: ${SPRING_SECURITY_APP_DATASOURCE_USERNAME}
        password: ${SPRING_SECURITY_APP_DATASOURCE_PASSWORD} 
        driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS}
     
      owner: 
        max-lifetime: ${SPRING_DATASOURCE_MAX_LIFETIME}
        maximum-pool-size: ${SPRING_DATASOURCE_MAX_POOL_SIZE} 
        connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT}
        minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE}
        url: ${SPRING_SECURITY_DATASOURCE_URL}
        username: ${SPRING_SECURITY_OWN_DATASOURCE_USERNAME}
        password: ${SPRING_SECURITY_OWN_DATASOURCE_PASSWORD}
        driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS} 
