package io.nzbee.util.inventory;

public class InventoryLocationMasterSchema {
	
	private String INVENTORY_LOCATION_CODE;
	
	private String INVENTORY_LOCATION_DESC;
		
	private String INVENTORY_LOCATION_IS_ACTIVE;

	public String get_INVENTORY_LOCATION_CODE() {
		return INVENTORY_LOCATION_CODE;
	}

	public void set_INVENTORY_LOCATION_CODE(String iNVENTORY_LOCATION_CODE) {
		INVENTORY_LOCATION_CODE = iNVENTORY_LOCATION_CODE;
	}

	public String get_INVENTORY_LOCATION_DESC() {
		return INVENTORY_LOCATION_DESC;
	}

	public void set_INVENTORY_LOCATION_DESC(String iNVENTORY_LOCATION_DESC) {
		INVENTORY_LOCATION_DESC = iNVENTORY_LOCATION_DESC;
	}

	public String get_INVENTORY_LOCATION_IS_ACTIVE() {
		return INVENTORY_LOCATION_IS_ACTIVE;
	}

	public void set_INVENTORY_LOCATION_IS_ACTIVE(String iNVENTORY_LOCATION_IS_ACTIVE) {
		INVENTORY_LOCATION_IS_ACTIVE = iNVENTORY_LOCATION_IS_ACTIVE;
	}
	
}
