package io.nzbee.util.inventory;

public class InventoryMasterSchema {

	
	private String INVENTORY_LOCATION_CODE;
		
	private String INVENTORY_PRODUCT_UPC;
	
	private Long INVENTORY_QUANTITY;
	
	private double INVENTORY_PRICE;
	
	private String INVENTORY_CURRENCY_CODE;
	
	private String INVENTORY_TYPE_CODE;
	
	private String INVENTORY_SUPPLIER_ID;
	
	private String INVENTORY_TRANSACTION_DATE;

	public String get_INVENTORY_LOCATION_CODE() {
		return INVENTORY_LOCATION_CODE;
	}

	public void set_INVENTORY_LOCATION_CODE(String INVENTORY_LOCATION_CODE) {
		this.INVENTORY_LOCATION_CODE = INVENTORY_LOCATION_CODE;
	}

	public String get_INVENTORY_PRODUCT_UPC() {
		return INVENTORY_PRODUCT_UPC;
	}

	public void set_INVENTORY_PRODUCT_UPC(String INVENTORY_PRODUCT_UPC) {
		this.INVENTORY_PRODUCT_UPC = INVENTORY_PRODUCT_UPC;
	}

	public Long get_INVENTORY_QUANTITY() {
		return this.INVENTORY_QUANTITY;
	}

	public void set_INVENTORY_QUANTITY(Long INVENTORY_QUANTITY) {
		this.INVENTORY_QUANTITY = INVENTORY_QUANTITY;
	}

	public double get_INVENTORY_PRICE() {
		return this.INVENTORY_PRICE;
	}

	public void set_INVENTORY_PRICE(double INVENTORY_PRICE) {
		this.INVENTORY_PRICE = INVENTORY_PRICE;
	}

	public String get_INVENTORY_CURRENCY_CODE() {
		return INVENTORY_CURRENCY_CODE;
	}

	public void set_INVENTORY_CURRENCY_CODE(String INVENTORY_CURRENCY_CODE) {
		this.INVENTORY_CURRENCY_CODE = INVENTORY_CURRENCY_CODE;
	}

	public String get_INVENTORY_TYPE_CODE() {
		return INVENTORY_TYPE_CODE;
	}

	public void set_INVENTORY_TYPE_CODE(String INVENTORY_TYPE_CODE) {
		this.INVENTORY_TYPE_CODE = INVENTORY_TYPE_CODE;
	}

	public String get_INVENTORY_SUPPLIER_ID() {
		return INVENTORY_SUPPLIER_ID;
	}

	public void set_INVENTORY_SUPPLIER_ID(String INVENTORY_SUPPLIER_ID) {
		this.INVENTORY_SUPPLIER_ID = INVENTORY_SUPPLIER_ID;
	}

	public String get_INVENTORY_TRANSACTION_DATE() {
		return INVENTORY_TRANSACTION_DATE;
	}

	public void set_INVENTORY_TRANSACTION_DATE(String INVENTORY_TRANSACTION_DATE) {
		this.INVENTORY_TRANSACTION_DATE = INVENTORY_TRANSACTION_DATE;
	}
	
}
