import io.nzbee.domain.bag.Bag;
import io.nzbee.domain.bag.item.BagItem;
import io.nzbee.domain.bag.item.DroolsBagItemWrapper;
import java.util.List;
import org.apache.tomcat.util.buf.StringUtils;

//dialect "mvel"

function String pendingItemKey(DroolsBagItemWrapper bagItem) { 
	return bagItem.getCustomerId() + "-"+ bagItem.getProductUPC();
}


rule "Is Out-Of Stock"
when
$bagItem : DroolsBagItemWrapper(!bagItemStatus.equals("PRO01") && !isInStock())
then
System.out.println("\nIs Out-Of Stock Rule");
System.out.println("************************************");
String error = "Can't process " +  $bagItem.getProductUPC() + " is Out-Of-Stock" ;
System.out.println(error);
$bagItem.getBag().setErrors(true);
$bagItem.getBag().setError(error);
$bagItem.logItemError(pendingItemKey($bagItem), $bagItem.getBagItem());
end


rule "Item quantity exceeds limit"
when 
$bagItem : DroolsBagItemWrapper(	!bagItemStatus.equals("PRO01")
									&& bagItemQuantity > 6)
then 
String error = "Can't process " +  $bagItem.getProductUPC() + ", quantity " + $bagItem.getBagItemQuantity() + " is more than the maximum allowed" ;
System.out.println(error);
$bagItem.getBag().setErrors(true);
$bagItem.getBag().setError(error);
$bagItem.logItemError(pendingItemKey($bagItem), $bagItem.getBagItem());
end

rule "Item quantity below minimum"
when 
$bagItem : DroolsBagItemWrapper(!bagItemStatus.equals("PRO01")
								&& bagItemQuantity < 1)
then 
String error = "Can't process " +  $bagItem.getProductUPC() + ", quantity " + $bagItem.getBagItemQuantity() + " is below minimum allowed" ;
System.out.println(error);
$bagItem.getBag().setErrors(true);
$bagItem.getBag().setError(error);
$bagItem.logItemError(pendingItemKey($bagItem), $bagItem.getBagItem());
end

rule "Bag quantity exceeds limit"
when  
$bagItem : DroolsBagItemWrapper(getBag().getTotalQuantity() > 50)
then 
String error = "Can't process " +  $bagItem.getProductUPC() + ", bag quantity " + $bagItem.getBagItemQuantity() + " is more than the maximum allowed" ;
$bagItem.getBag().setErrors(true);
$bagItem.getBag().setError(error);
$bagItem.logItemError(pendingItemKey($bagItem), $bagItem.getBagItem());
end