import io.nzbee.domain.promotion.bag.item.PromotionDiscountItem;
import io.nzbee.domain.promotion.bag.DroolsPromotionBagItemWrapper;
import io.nzbee.domain.valueObjects.PromotionCode;
import io.nzbee.domain.valueObjects.Money;
import java.util.List;
import java.math.BigDecimal;
import org.apache.tomcat.util.buf.StringUtils;

dialect "mvel"

rule "Buy 2 get 1 free"
when 
$bagItem : DroolsPromotionBagItemWrapper(getBagItemQuantity().amount().intValue() >= 2 && getCouponCodes().contains("B2G50"))
then  
System.out.println("current quantity = " + $bagItem.getBagItemQuantity().amount().toString());
System.out.println("current price = " + $bagItem.getBagItemPrice());
System.out.println("promotion = \"Buy 2 get 50% off\"");
Double discPctg = (((Math.floor($bagItem.getBagItemQuantity().divide(new Long(2)))*2)/$bagItem.getBagItemQuantity().amount().intValue()) * 0.5);
System.out.println("discount percentage is = " + discPctg);
$bagItem.addDiscount(discPctg);
end


rule "Buy 3 get 1 free"
when 
$bagItem : DroolsPromotionBagItemWrapper(getBagItemQuantity().amount().intValue() >= 3 && getCouponCodes().contains("B3G33"))
then  
System.out.println("current quantity = " + $bagItem.getBagItemQuantity().amount().toString());
System.out.println("current price = " + $bagItem.getBagItemPrice());
System.out.println("promotion = \"Buy 3 get 33% off\"");
Double discPctg = (((Math.floor($bagItem.getBagItemQuantity().divide(new Long(3)))*3)/$bagItem.getBagItemQuantity().amount().intValue()) * 0.333333);
System.out.println("discount percentage is = " + discPctg);
$bagItem.addDiscount(discPctg);
end
/*
rule "If spend over $500 then 10% off"
when 
then
end
*/