import io.nzbee.domain.promotion.bag.item.PromotionDiscountItem;
import io.nzbee.domain.promotion.bag.DroolsPromotionBagItemWrapper;
import io.nzbee.domain.valueObjects.PromotionCode;
import io.nzbee.domain.valueObjects.Money;
import java.util.List;
import java.math.BigDecimal;
import org.apache.tomcat.util.buf.StringUtils;

dialect "mvel"

rule "Buy 2 get 1 free"
when 
$bagItem : DroolsPromotionBagItemWrapper(getBagItemQuantity() >= 2 && getCouponCodes().contains("B2G50"))
then  
System.out.println("current quantity = " + $bagItem.getBagItemQuantity());
System.out.println("current price = " + $bagItem.getBagItemPrice());
System.out.println("promotion = \"Buy 2 get 50% off\"");
System.out.println("total line amount = " + $bagItem.getBagItemQuantity() * $bagItem.getBagItemPrice().doubleValue());
Double discAmt = new Double((Math.floor($bagItem.getBagItemQuantity() / 2) * $bagItem.getBagItemPrice().doubleValue()));
System.out.println("discount amount is = " + discAmt);
$bagItem.addDiscount(discAmt);
end

/*
rule "Buy 3 get 1 free"
when 
$bagItem : DroolsPromotionBagItemWrapper(isInStock() && promotionCodes.contains("B3G33") && bagItemQuantity >= 2)
then  
System.out.println("promotion codes = " + StringUtils.join($bagItem.getPromotionCodes()));
System.out.println("current quantity = " + $bagItem.getBagItemQuantity());
System.out.println("promotion = \"Buy 3 get 33% off\"");
System.out.println("total line amount = " + $bagItem.getBagItemQuantity() * $bagItem.getMarkdownPrice());
Double discAmt = new Double((Math.floor($bagItem.getBagItemQuantity() / 3) * $bagItem.getMarkdownPrice()));
System.out.println("discount amount is = " + discAmt);
Discount discount = new Discount($bagItem.getBagItem(), $bagItem.getPromotion("B3G33"), discAmt);
$bagItem.addDiscount(discount);
end

rule "If spend over $500 then 10% off"
when 
then
end
*/